In [44]:
# Employee Salary Analysis System
# Dataset
import numpy as np

employee_id = np.array([
101,102,103,104,105,
106,107,108,109,110,
111,112,113,114,115,
116,117,118,119,120
])

department = np.array([
"IT","HR","Sales","IT","Finance",
"HR","Sales","IT","Marketing","Finance",
"IT","HR","Sales","Marketing","Finance",
"IT","Sales","HR","Finance","Marketing"
])

salary = np.array([
45000,35000,52000,61000,48000,
39000,55000,72000,43000,50000,
68000,36000,58000,47000,51000,
75000,62000,40000,54000,46000
])

experience = np.array([
2,1,4,6,3,
2,5,8,2,4,
7,1,6,3,5,
9,7,2,5,4
])



In [45]:
# Total Employees
print("Total Employees:", len(employee_id))


Total Employees: 20


In [46]:
# Average Salary
print("Average Salary:", np.mean(salary))


Average Salary: 51850.0


In [47]:
# Highest Salary
print("Highest Salary:", np.max(salary))

Highest Salary: 75000


In [48]:
# Lowest Salary
print("Lowest Salary:", np.min(salary))

Lowest Salary: 35000


In [49]:
# Median Salary
print("Median Salary:", np.median(salary))

Median Salary: 50500.0


In [50]:
# Standard Deviation
print("Standard Deviation:", np.std(salary))

Standard Deviation: 11145.739096174824


In [51]:

# Employees earning above ₹60,000
high_salary = salary[salary > 60000]

print(high_salary)

[61000 72000 68000 75000 62000]


In [52]:
# Employees earning below ₹40,000
print(salary[salary < 40000])

[35000 39000 36000]


In [53]:
# Give everyone a 10% salary increment
increment = salary * 1.10

print(increment)

[49500. 38500. 57200. 67100. 52800. 42900. 60500. 79200. 47300. 55000.
 74800. 39600. 63800. 51700. 56100. 82500. 68200. 44000. 59400. 50600.]


In [54]:
# Calculate 5% Tax
tax = salary * 0.05

print(tax)

[2250. 1750. 2600. 3050. 2400. 1950. 2750. 3600. 2150. 2500. 3400. 1800.
 2900. 2350. 2550. 3750. 3100. 2000. 2700. 2300.]


In [55]:
# Net Salary
net_salary = salary - tax

print(net_salary)

[42750. 33250. 49400. 57950. 45600. 37050. 52250. 68400. 40850. 47500.
 64600. 34200. 55100. 44650. 48450. 71250. 58900. 38000. 51300. 43700.]


In [56]:
# Find IT Department Employees
it_salary = salary[department == "IT"]

print(it_salary)

[45000 61000 72000 68000 75000]


In [57]:
# Employees with More Than 5 Years Experience
print(employee_id[experience > 5])

[104 108 111 113 116 117]
